name: CI

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  build:
    name: ${{ matrix.task.name}} - ${{ matrix.os.name }} ${{ matrix.python.name }}
    runs-on: ${{ matrix.os.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: Linux
            runs-on: ubuntu-latest
        python:
          - name: CPython 3.9
            tox: py39
            action: 3.9
        task:
          - name: Build
            tox: build

    steps:
    - uses: actions/checkout@v3

    - name: Set up ${{ matrix.python.name }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python.action }}

    - name: Install dependencies
      run: python -m pip install --upgrade pip tox

    - uses: twisted/python-info-action@v1

    - name: Tox
      run: tox -c tox.ini -e ${{ matrix.task.tox }}

    - name: Publish
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/

  test-linux:
    name: ${{ matrix.task.name}} - Linux ${{ matrix.python.name }}
    runs-on: ubuntu-latest
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        python:
          - name: CPython 3.7
            tox: py37
            action: 3.7
          - name: CPython 3.8
            tox: py38
            action: 3.8
          - name: CPython 3.9
            tox: py39
            action: 3.9
          - name: CPython 3.10
            tox: py310
            action: '3.10'
          - name: PyPy 3.7
            tox: pypy37
            action: pypy-3.7
          - name: PyPy 3.8
            tox: pypy38
            action: pypy-3.8
        task:
          - name: Test
            tox: tests

    steps:
    - uses: actions/checkout@v3

    - name: Download package files
      uses: actions/download-artifact@v3
      with:
        name: dist
        path: dist/

    - name: Set up ${{ matrix.python.name }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python.action }}

    - name: Install dependencies
      run: python -m pip install --upgrade pip tox codecov

    - uses: twisted/python-info-action@v1

    - name: Tox
      run: tox -c tox.ini --installpkg dist/*.whl -e ${{ matrix.python.tox }}-tests

    - name: Codecov
      run: |
        codecov -n "GitHub Actions - ${{ matrix.task.name}} - ${{ matrix.os.name }} ${{ matrix.python.name }}"


  test-windows:
    name: ${{ matrix.task.name}} - Windows ${{ matrix.python.name }}
    runs-on: windows-latest
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        python:
          - name: CPython 3.9
            tox: py39
            action: '3.9'
        task:
          - name: Test
            tox: tests

    steps:
    - uses: actions/checkout@v3

    - name: Download package files
      uses: actions/download-artifact@v3
      with:
        name: dist
        path: dist/

    - name: Set up ${{ matrix.python.name }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python.action }}

    - name: Install dependencies
      run: python -m pip install --upgrade pip tox codecov

    - uses: twisted/python-info-action@v1

    - name: Tox
      run: tox -c tox.ini --installpkg dist/*.whl -e ${{ matrix.python.tox }}-tests

    - name: Codecov
      run: |
        codecov -n "GitHub Actions - ${{ matrix.task.name}} - ${{ matrix.os.name }} ${{ matrix.python.name }}"

  check:
    name: ${{ matrix.task.name}} - ${{ matrix.python.name }}
    runs-on: ubuntu-latest
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        python:
          # Using second most recent minor release for whatever little
          # increase in stability over using the latest minor.
          - name: CPython 3.9
            tox: py39
            action: 3.9
        task:
          - name: Check Newsfragment
            tox: check-newsfragment

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Download package files
      uses: actions/download-artifact@v3
      with:
        name: dist
        path: dist/

    - name: Set up ${{ matrix.python.name }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python.action }}

    - name: Install dependencies
      run: python -m pip install --upgrade pip tox

    - uses: twisted/python-info-action@v1

    - name: Tox
      run: tox -c tox.ini -e ${{ matrix.task.tox }}

  pypi-publish:
    # https://github.community/t/is-it-possible-to-require-all-github-actions-tasks-to-pass-without-enumerating-them/117957/4?u=graingert
    name: Check tag and publish
    runs-on: ubuntu-latest

    needs:
      - build
      - test-linux
      - test-windows
    steps:
    - uses: actions/checkout@v3

    - name: Download package files
      uses: actions/download-artifact@v3
      with:
        name: dist
        path: dist/

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install pep517

    - name: Display structure of files to be pushed
      run: ls --recursive dist/

    - name: Check matched tag version and branch version - on tag
      if: startsWith(github.ref, 'refs/tags/')
      run: python admin/check_tag_version_match.py "${{ github.ref }}"

    - name: Publish to PyPI - on tag
      if: startsWith(github.ref, 'refs/tags/')
      uses: pypa/gh-action-pypi-publish@v1.4.2
      with:
        password: ${{ secrets.PYPI_TOKEN }}
        verbose: true

  # This is a meta-job to simplify PR CI enforcement configuration in GitHub.
  # Inside the GitHub config UI you only configure this job as required.
  # All the extra requirements are defined "as code" as part of the `needs`
  # list for this job.
  all:
    name: All success
    runs-on: ubuntu-latest
    # The always() part is very important.
    # If not set, the job will be skipped on failing dependencies.
    if: always()
    needs:
      # This is the list of CI job that we are interested to be green before
      # a merge.
      - build
      - test-linux
      - test-windows
      - check
      - pypi-publish
    steps:
      - name: Require all successes
        shell: python
        env:
          RESULTS: ${{ toJSON(needs.*.result) }}
        run: |
          import json
          import os
          import sys
          results = json.loads(os.environ["RESULTS"])
          sys.exit(0 if all(result == "success" for result in results) else 1)
